typography_spectrum: 0.721284
color:
  brandColors:
    - '#C0C0B0'
    - '#000000'
    - '#988868'
    - '#000000'
    - '#000000'
  brandStrength: 0.5
  lightness: 0.8125
  saturation: 0.5625
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.09094
analytics:
  google: null
  facebook: null
  twitter: null
name: Service Design by Labshare
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Open Innovation Platform
    url: 'http://www.labsharegroup.com/'
    type: external
  - name: Business Architecture
    url: 'http://www.buildventure.net/'
    type: external
favicon: null
title: Design engineering services by service design and business architecture
description: Experience Design
purpose: []
