typography_spectrum: 0.7384696779772639
color:
  brandColors:
    - '#FCFFF5'
    - '#D1DBBD'
    - '#91AA9D'
    - '#3E606F'
    - '#193441'
  brandStrength: 0.666738721774891
  lightness: 0.39532990474253893
  saturation: 0.8878972819074988
  rhythmicContrast: 0.8317527801264077
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.5612643952481449
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: tibor zahorecz
  email: tibor.zahorecz@dosell.io
  url: 'http://www.labsharegroup.com/'
name: Service Design by Labshare
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Open Innovation Platform
    url: 'http://www.labsharegroup.com/'
    type: external
  - name: Business Architecture
    url: 'http://www.buildventure.net/'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/e60aea7c-8866-4cf8-9b92-989ea90a5507.jpg
title: Design engineering services by service design and business architecture
description: Experience Design
purpose: []
