name: Service Design by Labshare
favicon: null
layout_spectrum: 0.4359681489877403
typography_spectrum: 0.47572629479691386
title: Design engineering services by service design and business architecture
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.012802981305867434
  lightness: 0.06585901114158332
  saturation: 0.40732597932219505
  rhythmicContrast: 0.9422789274249226
purpose: []
