name: Service Design by Labshare
favicon: null
layout_spectrum: 0.09094
typography_spectrum: 0.721284
title: Design engineering services by service design and business architecture
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#C0C0B0'
    - '#000000'
    - '#988868'
    - '#000000'
    - '#000000'
  brandStrength: 0.5
  lightness: 0.8125
  saturation: 0.5625
  rhythmicContrast: 0.5
purpose: []
