analytics: {}
color:
  brandColors:
    - '#C0C0B0'
    - '#000000'
    - '#988868'
    - '#000000'
    - '#000000'
  brandStrength: 0.5
  lightness: 0.8125
  rhythmicContrast: 0.5
  saturation: 0.5625
cta: {}
layout_spectrum: 0.09094
name: Service Design by Labshare
opengraph: {}
purpose: []
typography_spectrum: 0.721284
